# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/jazzband/pip-tools
    rev: 6.3.0
    hooks:
    -   id: pip-compile
        name: pip-compile prod.in
        args: [requirements/prod.in]
        files: ^requirements/prod\.(in|txt)$
    -   id: pip-compile
        name: pip-compile dev.in
        args: [requirements/dev.in]
        files: ^requirements/dev\.(in|txt)$
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
